name: Update Visitors Count

on:
  schedule:
    - cron: "0 */12 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
       
      - name: Fetch visitor count
        run: |
          VISITOR_COUNT=$(curl -s "https://analytics.mauch.rocks/matomo/index.php?module=API&method=VisitsSummary.get&idSite=1&period=year&date=today&format=JSON&token_auth=a10ec06fb156efa4274fe4c06646c23f" | jq '.nb_visits')
          echo "$VISITOR_COUNT" > /home/runner/work/personal/personal/content/visitors.txt
        
      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add content/visitors.txt
          git commit -m "Update visitors.txt"        
          git push

      - name: Trigger another deploy hugo workflow
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/MichiMauch/personal/actions/workflows/hugo.yml/dispatches \
            -d '{"ref":"main"}'