name: Update Visitors Count

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Test echo
      run: echo "Hello, this is a test echo!"

    - name: Check curl output
      run: |
        curl "https://analytics.mauch.rocks/matomo/index.php?module=API&method=VisitsSummary.get&idSite=1&period=day&date=today&format=JSON&token_auth=a10ec06fb156efa4274fe4c06646c23f"

    - name: Check directory and permissions
      run: |
        ls -al /home/runner/work/personal/personal/content
        mkdir -p /home/runner/work/personal/personal/content

    - name: Read the file
      run: |
        cat /home/runner/work/personal/personal/content/visitors.txt
      
    - name: Fetch visitor count
      run: |
        VISITOR_COUNT=$(curl -s "https://analytics.mauch.rocks/matomo/index.php?module=API&method=VisitsSummary.get&idSite=1&period=day&date=today&format=JSON&token_auth=a10ec06fb156efa4274fe4c06646c23f" | jq '.nb_visits')
        echo "VISITOR_COUNT: $VISITOR_COUNT"  # Diese Zeile wird den Wert im Log ausgeben
        echo "VISITOR_COUNT=$VISITOR_COUNT" >> $GITHUB_ENV
      
    - name: Update Hugo content with visitor count
      run: |
        echo $VISITOR_COUNT > /home/runner/work/personal/personal/content/visitors.txt  # Oder wo immer du die Daten in deinem Hugo-Projekt speichern möchtest
